version: '3.8'
services:
  web:
    build:
      context: ./docker/nginx
      target: nginx_develop
    depends_on:
      - app
    volumes:
      - ./public:/var/www/html/public:cached
      - ./storage/app/public:/var/www/html/public/storage:cached
    ports:
      - 8231:80
    networks:
      - default
  app:
    hostname: app-sv
    build:
      context: docker/php-fpm
      target: php_fpm_develop
    depends_on:
      - db
      - redis
    volumes:
      - .:/var/www/html:cached
    networks:
      - default
    environment:
      PHP_IDE_CONFIG: "serverName=MyApp"
  db:
    build:
      context: ./docker/mysql
    volumes:
      - db_data:/var/lib/mysql:cached
      - ./storage/logs/mysql:/var/log/mysql:cached
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--skip-character-set-client-handshake',
      '--collation-server=utf8mb4_general_ci',
      #      '--general-log=1',
      #      '--general-log-file=/var/log/mysql/query.log',
      '--slow-query-log=1',
      '--long-query-time=1',
      '--slow-query-log-file=/var/log/mysql/slow.log',
      '--log-queries-not-using-indexes=0',
      '--log-timestamps=SYSTEM'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root!password?
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - default
  composer:
    image: 'composer:2'
    volumes:
      - ./:/app
    command: 'composer install'
  redis:
    image: redis:5.0.7
    ports:
      - 63233:6379
  smtp:
    image: mailhog/mailhog
    ports:
      - 8234:8025

volumes:
  db_data:
